apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project
  labels:
    app: capstone-project
  namespace: default
spec:
  progressDeadlineSeconds: 3600
  replicas: 3
  selector:
    matchLabels:
      app: capstone-project
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
        - image: minhng130300/capstone-project:v2
          imagePullPolicy: Always
          name: capstone-project
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project
  labels:
    app: capstone-project
spec:
  type: LoadBalancer
  selector:
    app: capstone-project
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
